# Generated by Django 4.2 on 2026-06-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='house',
            name='status',
        ),
        migrations.AddField(
            model_name='house',
            name='area_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='house',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/'),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='house',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='projects.project'),
        ),
    ]
