"""Add audit details to system logs

Revision ID: 15b9bb16581c
Revises: 7972de4ccce2
Create Date: 2026-09-13 12:07:12.888021
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15b9bb16581c'
down_revision: Union[str, None] = '7972de4ccce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('system_logs', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('system_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('system_logs', sa.Column('details', sa.Text(), nullable=True))
    op.create_foreign_key('fk_system_logs_user_id', 'system_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_system_logs_user_id', 'system_logs', type_='foreignkey')
    op.drop_column('system_logs', 'details')
    op.drop_column('system_logs', 'entity_id')
    op.drop_column('system_logs', 'entity_type')
    op.drop_column('system_logs', 'user_id')
    # ### end Alembic commands ###
